import { Router } from "express";
import { layer10Service } from "../regen/regen.service.js";

const router = Router();

// GET /api/fields/:fieldId/regen/planning
// Returns a field-specific regenerative agriculture plan generated by AI.
router.get("/:fieldId/regen/planning", async (req, res, next) => {
  try {
    const { fieldId } = req.params;
    const plan = await layer10Service.getRegenPlan(fieldId);
    res.json({
      ...plan,
      plan_status: "Active",
    });
  } catch (error) {
    next(error);
  }
});

export default router;
