-- AgriMesh Migration 015: Add irrigation_type to fields table
-- [DEAD CODE REMOVED] This migration is a duplicate of 014_advisory_evidence.sql
-- which already added irrigation_type to the fields table.
-- The file is preserved as a tombstone so the migration runner skips it gracefully.
