import { FieldHealthScore, DimensionResult, Severity } from './health-score.types';
import { satelliteStore } from '../satellite/satellite.store';

export class HealthScoreService {
  
  async computeScore(fieldId: string): Promise<FieldHealthScore> {
    // 1. Fetch real Satellite Data (Layer 05)
    const latestTile = await satelliteStore.getLatestTile(fieldId);
    const latestTrend = await satelliteStore.getLatestTrend(fieldId);
    const activeAnomalies = await satelliteStore.getActiveAnomalies(fieldId);

    // 2. Generate deterministic mock data for upstream layers we haven't built yet
    // Layer 02: Crop Stage Mock
    const mockCropStage = {
      stage: 'Flowering',
      waterNeed: 'High',
      diseaseSusceptibility: 'Moderate'
    };

    // Layer 03: Weather Mock
    const mockWeather = {
      recentRainfallMm: latestTile && latestTile.cloudCoverPct > 20 ? 15 : 0, // correlate rain with recent clouds
      forecastRainfallMm: 0,
      forecastHighTemp: 34,
      humidityAvg: 65,
      activeFlags: [] as string[]
    };
    if (mockWeather.forecastHighTemp > 35) mockWeather.activeFlags.push('heat_event_expected');

    // Layer 04: Soil Mock
    const mockSoil = {
      texture: 'sandy_loam',
      waterHoldingCapacity: 'low',
      nitrogenLevel: 'medium'
    };

    // 3. Compute Dimensions using explicit rules
    
    // --- Vegetation Trend (from Layer 05) ---
    const vegetationTrend = this.computeVegetationTrend(latestTrend, activeAnomalies);

    // --- Water Condition (Fusion: 03 Weather, 04 Soil, 05 Satellite, 02 Stage) ---
    const waterCondition = this.computeWaterCondition(mockWeather, mockSoil, latestTile, mockCropStage);

    // --- Soil Condition (Fusion: 04 Soil) ---
    const soilCondition = this.computeSoilCondition(mockSoil);

    // --- Weather Risk (Fusion: 03 Weather, 02 Stage) ---
    const weatherRisk = this.computeWeatherRisk(mockWeather, mockCropStage);

    // --- Disease Risk (Fusion: 03 Weather, 02 Stage, 05 Satellite) ---
    const diseaseRisk = this.computeDiseaseRisk(mockWeather, mockCropStage, activeAnomalies);

    // --- Climate Stress (Fusion: 03 Weather, 05 Satellite) ---
    const climateStress = this.computeClimateStress(mockWeather, activeAnomalies);

    // --- Overall Crop Health (Fusion of all above) ---
    const cropHealth = this.computeCropHealth([vegetationTrend, waterCondition, soilCondition, weatherRisk, diseaseRisk, climateStress]);

    // 4. Return Full Score (Synthesis text will be generated by Layer 09 later)
    return {
      fieldId,
      computedAt: new Date().toISOString(),
      crop_health: cropHealth,
      water_condition: waterCondition,
      soil_condition: soilCondition,
      weather_risk: weatherRisk,
      disease_risk: diseaseRisk,
      climate_stress: climateStress,
      vegetation_trend: vegetationTrend,
      synthesis_text: null // Layer 09 fills this
    };
  }

  // --- Dimension Computation Rules ---

  private computeVegetationTrend(latestTrend: any, activeAnomalies: any[]): DimensionResult {
    const basis: string[] = [];
    let severity: Severity = 'green';
    let value = 'Stable';

    if (activeAnomalies.length > 0) {
      severity = activeAnomalies.some(a => a.severity === 'high') ? 'red' : 'amber';
      value = 'Decline detected';
      basis.push(`Satellite anomaly detected in ${activeAnomalies.length} sub-region(s)`);
    } else if (latestTrend) {
      if (latestTrend.ndviTrendDirection === 'improving') {
        value = 'Improving';
        basis.push('Field-wide NDVI is increasing compared to last pass');
      } else if (latestTrend.ndviTrendDirection === 'declining') {
        severity = 'amber';
        value = 'Slight decline';
        basis.push('Field-wide NDVI showed slight decline, monitoring closely');
      } else {
        basis.push('Vegetation index is stable across the field');
      }
    } else {
      basis.push('No recent satellite data available to confirm trend');
    }

    return { value, severity, basis };
  }

  private computeWaterCondition(weather: any, soil: any, tile: any, stage: any): DimensionResult {
    const basis: string[] = [];
    let severity: Severity = 'green';
    let value = 'Adequate';

    basis.push(`Crop is in ${stage.stage} stage requiring ${stage.waterNeed} water`);
    basis.push(`Soil has ${soil.waterHoldingCapacity} water holding capacity`);

    if (weather.recentRainfallMm < 5 && weather.forecastRainfallMm === 0 && soil.waterHoldingCapacity === 'low') {
      severity = 'amber';
      value = 'Drying';
      basis.push('No recent or forecast rain on low-retention soil');
    }
    
    if (tile && tile.moistureProxy < 0.3) {
      severity = 'red';
      value = 'Stressed';
      basis.push('Satellite surface moisture index is critically low');
    }

    return { value, severity, basis };
  }

  private computeSoilCondition(soil: any): DimensionResult {
    return {
      value: 'Moderate',
      severity: soil.nitrogenLevel === 'low' ? 'amber' : 'green',
      basis: [
        `Texture is ${soil.texture}`,
        `Nitrogen levels are estimated at ${soil.nitrogenLevel}`
      ]
    };
  }

  private computeWeatherRisk(weather: any, stage: any): DimensionResult {
    const basis: string[] = [];
    let severity: Severity = 'green';
    let value = 'Low Risk';

    if (weather.activeFlags.length > 0) {
      severity = 'amber';
      value = 'Elevated Risk';
      basis.push(`Active weather flags: ${weather.activeFlags.join(', ')}`);
    } else {
      basis.push('No severe weather events forecast in next 7 days');
    }

    if (weather.forecastHighTemp > 33 && stage.stage === 'Flowering') {
      severity = 'red';
      value = 'High Risk';
      basis.push('Heat during flowering can severely impact yield');
    }

    return { value, severity, basis };
  }

  private computeDiseaseRisk(weather: any, stage: any, anomalies: any[]): DimensionResult {
    const basis: string[] = [];
    let severity: Severity = 'green';
    let value = 'Low Risk';

    if (weather.humidityAvg > 80 && weather.recentRainfallMm > 10) {
      severity = 'amber';
      value = 'Elevated Risk';
      basis.push('High humidity and recent rain create fungal conditions');
    } else {
       basis.push('Current humidity and temperature do not favor major pathogens');
    }

    if (anomalies.some(a => a.anomalyType === 'vegetation_decline')) {
      basis.push('Existing vegetation decline could indicate active localized infection');
    }

    return { value, severity, basis };
  }

  private computeClimateStress(weather: any, anomalies: any[]): DimensionResult {
    // Distinguishing from short-term weather risk - looking at broader stress
    const basis: string[] = ['Temperatures are within normal seasonal range'];
    return { value: 'Normal', severity: 'green', basis };
  }

  private computeCropHealth(dimensions: DimensionResult[]): DimensionResult {
    const redCount = dimensions.filter(d => d.severity === 'red').length;
    const amberCount = dimensions.filter(d => d.severity === 'amber').length;
    
    let severity: Severity = 'green';
    let value = 'Good';
    const basis: string[] = [];

    if (redCount > 0) {
      severity = 'red';
      value = 'Concern';
      basis.push(`${redCount} critical stress factors identified`);
    } else if (amberCount > 0) {
      severity = 'amber';
      value = 'Moderate';
      basis.push(`${amberCount} areas require attention`);
    } else {
      basis.push('All measured dimensions are within healthy ranges');
    }

    return { value, severity, basis };
  }
}

export const healthScoreService = new HealthScoreService();
